FROM node:20-alpine3.19
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente
COPY . .

# Exponer el puerto
EXPOSE 5173

# Comando para desarrollo con --host para exponer la red
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
