version: '3.8'
services:
  #-----------------------------------Base de datos operacional-----------------------------------
  posgrado:
    image: mysql:8.0
    container_name: posgrado_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root123!
      MYSQL_DATABASE: posgrado_db
      TZ: America/Santiago
    networks:
      - netmagister
    ports:
      - 3307:3306
    volumes:
      - posgrado_data:/var/lib/mysql
      - ./opsdb/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    command: --default-authentication-plugin=mysql_native_password
  #-----------------------------------Base de datos Autenticación-----------------------------------
  authdb:
    image: mysql:8.0
    container_name: authdb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root123!
      MYSQL_DATABASE: auth_db
      TZ: America/Santiago
    ports:
      - 3308:3306
    networks:
      - netmagister
    volumes:
      - authdb_data:/var/lib/mysql
      - ./authdb/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  posgrado_data:
  authdb_data:

networks:
  netmagister:
    driver: bridge
