services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root123!
      MYSQL_DATABASE: magister             # base principal inicial
      TZ: America/Santiago
    ports:
      - "3307:3306"                        # usa 3307 para evitar conflicto
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Root123!
      UPLOAD_LIMIT: 256M
    ports:
      - "8080:80"

volumes:
  mysql_data:
