FROM node:20-alpine3.19
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm install --global dotenv-cli
EXPOSE 5002
CMD ["dotenv", "--file", ".env.development", "node", "src/index.js"]