FROM node:20-alpine3.19
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install --global dotenv-cli
COPY . .
EXPOSE 5001
CMD ["dotenv", "--file", ".env.development", "node", "src/index.js"]
